export type KaomojiCategoryKey =
  | "happy"
  | "excited"
  | "proud"
  | "love"
  | "cute"
  | "laughing"
  | "smiling"
  | "blushing"
  | "peaceful"
  | "sad"
  | "crying"
  | "angry"
  | "disappointed"
  | "scared"
  | "frustrated"
  | "tired"
  | "sick"
  | "shrug"
  | "facepalm"
  | "tableFlip"
  | "tableFix"
  | "shocked"
  | "confused"
  | "thinking"
  | "sleeping"
  | "kawaii"
  | "senpai"
  | "catGirls"
  | "chibi"
  | "magical"
  | "hero"
  | "cats"
  | "bears"
  | "dogs"
  | "rabbits"
  | "foxes"
  | "birds"
  | "victory"
  | "defeat"
  | "rage"
  | "gg"
  | "afk"
  | "clutch"
  | "hug"
  | "kiss"
  | "couples"
  | "friendship"
  | "heartbreak"
  | "halloween"
  | "christmas";

export interface KaomojiEntry {
  id: string;
  expression: string;
  name: string;
  slug: string;
  category: KaomojiCategoryKey;
  emotion: string;
  tags: string[];
  collections: string[];
  popularity: number;
  relatedSlugs: string[];
  keywords: string[];
  meaning?: string;
  commonUses?: string[];
  examples?: string[];
}
