version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    security-updates: true
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
