import type { PlatformId, PlatformRules } from "./types";

export const PLATFORMS: Record<PlatformId, PlatformRules> = {
  instagram: {
    id: "instagram",
    name: "Instagram",
    category: "Social",
    maxLen: 30,
    minLen: 1,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: [".", "_"],
    restrictedWords: ["admin", "instagram"],
    recommendedLength: "6 - 15 chars",
  },
  tiktok: {
    id: "tiktok",
    name: "TikTok",
    category: "Social",
    maxLen: 24,
    minLen: 2,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: [".", "_"],
    restrictedWords: ["tiktok"],
    recommendedLength: "4 - 12 chars",
  },
  discord: {
    id: "discord",
    name: "Discord",
    category: "Social",
    maxLen: 32,
    minLen: 2,
    allowUnicode: true,
    allowSpaces: true,
    allowEmoji: true,
    allowedSymbols: [".", "_", "-", "#"],
    restrictedWords: ["discord", "everyone", "here"],
    recommendedLength: "3 - 16 chars",
  },
  freeFire: {
    id: "freeFire",
    name: "Free Fire",
    category: "Gaming",
    maxLen: 12,
    minLen: 3,
    allowUnicode: true,
    allowSpaces: false,
    allowEmoji: true,
    allowedSymbols: ["ツ", "×", "•", "★", "〆", "乂", "么", "彡"],
    restrictedWords: ["garena"],
    recommendedLength: "6 - 10 chars",
  },
  pubg: {
    id: "pubg",
    name: "PUBG Mobile",
    category: "Gaming",
    maxLen: 14,
    minLen: 3,
    allowUnicode: true,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["ī", "丨", "父", "神", "٭"],
    restrictedWords: ["pubg"],
    recommendedLength: "7 - 12 chars",
  },
  bgmi: {
    id: "bgmi",
    name: "BGMI",
    category: "Gaming",
    maxLen: 14,
    minLen: 3,
    allowUnicode: true,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["ī", "丨", "父", "神", "٭"],
    restrictedWords: ["krafton"],
    recommendedLength: "7 - 12 chars",
  },
  valorant: {
    id: "valorant",
    name: "Valorant",
    category: "Gaming",
    maxLen: 16,
    minLen: 3,
    allowUnicode: false,
    allowSpaces: true,
    allowEmoji: false,
    allowedSymbols: [],
    restrictedWords: ["riot"],
    recommendedLength: "5 - 12 chars",
  },
  roblox: {
    id: "roblox",
    name: "Roblox",
    category: "Gaming",
    maxLen: 20,
    minLen: 3,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["_"],
    restrictedWords: ["roblox"],
    recommendedLength: "5 - 15 chars",
  },
  minecraft: {
    id: "minecraft",
    name: "Minecraft",
    category: "Gaming",
    maxLen: 16,
    minLen: 3,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["_"],
    restrictedWords: ["mojang"],
    recommendedLength: "4 - 12 chars",
  },
  youtube: {
    id: "youtube",
    name: "YouTube",
    category: "Creator",
    maxLen: 30,
    minLen: 3,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: [".", "_", "-"],
    restrictedWords: ["youtube"],
    recommendedLength: "6 - 15 chars",
  },
  twitch: {
    id: "twitch",
    name: "Twitch",
    category: "Creator",
    maxLen: 25,
    minLen: 4,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["_"],
    restrictedWords: ["twitch"],
    recommendedLength: "5 - 14 chars",
  },
  x: {
    id: "x",
    name: "X (Twitter)",
    category: "Social",
    maxLen: 15,
    minLen: 4,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["_"],
    restrictedWords: ["twitter", "admin"],
    recommendedLength: "4 - 12 chars",
  },
  threads: {
    id: "threads",
    name: "Threads",
    category: "Social",
    maxLen: 30,
    minLen: 1,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: [".", "_"],
    restrictedWords: ["threads"],
    recommendedLength: "6 - 15 chars",
  },
  fortnite: {
    id: "fortnite",
    name: "Fortnite",
    category: "Gaming",
    maxLen: 16,
    minLen: 3,
    allowUnicode: true,
    allowSpaces: true,
    allowEmoji: false,
    allowedSymbols: ["-", "_"],
    restrictedWords: ["epic"],
    recommendedLength: "5 - 14 chars",
  },
  cod: {
    id: "cod",
    name: "COD Mobile",
    category: "Gaming",
    maxLen: 14,
    minLen: 2,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["-", "_"],
    restrictedWords: ["activision"],
    recommendedLength: "5 - 12 chars",
  },
  steam: {
    id: "steam",
    name: "Steam",
    category: "Gaming",
    maxLen: 32,
    minLen: 2,
    allowUnicode: true,
    allowSpaces: true,
    allowEmoji: true,
    allowedSymbols: ["_", "-", "."],
    restrictedWords: ["valve", "steam"],
    recommendedLength: "4 - 16 chars",
  },
  kick: {
    id: "kick",
    name: "Kick",
    category: "Creator",
    maxLen: 25,
    minLen: 3,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["_"],
    restrictedWords: ["kick"],
    recommendedLength: "5 - 14 chars",
  },
  github: {
    id: "github",
    name: "GitHub",
    category: "Professional",
    maxLen: 39,
    minLen: 1,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["-"],
    restrictedWords: ["github"],
    recommendedLength: "4 - 15 chars",
  },
  linkedin: {
    id: "linkedin",
    name: "LinkedIn",
    category: "Professional",
    maxLen: 30,
    minLen: 3,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["-"],
    restrictedWords: ["linkedin"],
    recommendedLength: "6 - 18 chars",
  },
  telegram: {
    id: "telegram",
    name: "Telegram",
    category: "Social",
    maxLen: 32,
    minLen: 5,
    allowUnicode: false,
    allowSpaces: false,
    allowEmoji: false,
    allowedSymbols: ["_"],
    restrictedWords: ["telegram"],
    recommendedLength: "5 - 16 chars",
  },
  whatsapp: {
    id: "whatsapp",
    name: "WhatsApp",
    category: "Social",
    maxLen: 25,
    minLen: 1,
    allowUnicode: true,
    allowSpaces: true,
    allowEmoji: true,
    allowedSymbols: ["_"],
    restrictedWords: [],
    recommendedLength: "3 - 15 chars",
  },
} as const;

export const PLATFORM_LIST = Object.values(PLATFORMS);
