export type SymbolCategoryKey =
  | "hearts"
  | "stars"
  | "arrows"
  | "decorative"
  | "linesBorders"
  | "boxes"
  | "mathematical"
  | "currency"
  | "technical"
  | "punctuation"
  | "shapes"
  | "chess"
  | "zodiac"
  | "weather"
  | "music"
  | "religion"
  | "emojiUnicode"
  | "greek"
  | "latinExtended"
  | "superscript"
  | "subscript"
  | "romanNumerals"
  | "braille"
  | "geometric"
  | "dingbats"
  | "miscellaneous";

export interface SymbolCopyVariant {
  label: string;
  value: string;
}

export interface SymbolBlock {
  key: string;
  name: string;
  category: SymbolCategoryKey;
  ranges: Array<[number, number]>;
}

export interface SymbolEntry {
  slug: string;
  codePoint: string;
  char: string;
  name: string;
  category: SymbolCategoryKey;
  subcategory?: string;
  block: string;
  tags: string[];
  unicodeVersion?: string;
  introducedIn?: string;
  featured?: boolean;
  seasonal?: boolean;
  searchWeight?: number;
  difficulty?: number;
  generalCategory?: string;
  aliases?: string[];
  altNames?: string[];
  synonyms?: string[];
  similarSlugs?: string[];
  copyVariants?: SymbolCopyVariant[];
  commonUses?: string[];
  browserSupportNote?: string;
  keywords: string[];
  popularity: number;
  autoGenerated?: boolean;
  utf8?: string;
  utf16?: string;
  cssEscape?: string;
  htmlEntityDec?: string;
  htmlEntityHex?: string;
  relatedTags?: string[];
  age?: string;
}
